# Generated by Django 5.1.3 on 2024-11-19 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(max_length=255, verbose_name="SMTP服务器"),
                ),
                ("smtp_port", models.IntegerField(verbose_name="SMTP端口")),
                (
                    "smtp_user",
                    models.CharField(max_length=255, verbose_name="SMTP用户名"),
                ),
                (
                    "smtp_password",
                    models.CharField(max_length=255, verbose_name="SMTP密码"),
                ),
                ("use_tls", models.BooleanField(default=True, verbose_name="使用TLS")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邮件配置",
                "verbose_name_plural": "邮件配置",
            },
        ),
        migrations.CreateModel(
            name="EmailForwardRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                (
                    "user_email",
                    models.EmailField(max_length=255, verbose_name="用户邮箱"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "forward_when_offline_only",
                    models.BooleanField(default=True, verbose_name="仅离线时转发"),
                ),
                (
                    "min_interval",
                    models.IntegerField(
                        default=300,
                        help_text="两次转发之间的最小间隔时间",
                        verbose_name="最小转发间隔(秒)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "转发规则",
                "verbose_name_plural": "转发规则",
            },
        ),
        migrations.CreateModel(
            name="EmailForwardLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.IntegerField(verbose_name="消息ID")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("private", "私信"), ("announcement", "公告")],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=255, verbose_name="接收者邮箱"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "forwarded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="转发时间"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forward_logs",
                        to="email.emailforwardrule",
                        verbose_name="转发规则",
                    ),
                ),
            ],
            options={
                "verbose_name": "转发日志",
                "verbose_name_plural": "转发日志",
                "ordering": ["-forwarded_at"],
            },
        ),
    ]
