# Generated by Django 5.1 on 2024-11-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldlogicrule',
            options={'ordering': ['priority'], 'verbose_name': '字段逻辑规则', 'verbose_name_plural': '字段逻辑规则'},
        ),
        migrations.RemoveField(
            model_name='fieldlogicrule',
            name='source_field',
        ),
        migrations.AddField(
            model_name='fieldlogicrule',
            name='condition_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='条件组'),
        ),
        migrations.AddField(
            model_name='fieldlogicrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='fieldlogicrule',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='fieldlogicrule',
            name='trigger_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_rules', to='conferenceApp.formfield', verbose_name='触发字段'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='附加信息'),
        ),
        migrations.AlterField(
            model_name='fieldlogicrule',
            name='action',
            field=models.CharField(choices=[('show', '显示'), ('hide', '隐藏'), ('enable', '启用'), ('disable', '禁用'), ('require', '必填'), ('unrequire', '非必填'), ('set_value', '设置值'), ('clear_value', '清除值')], max_length=20, verbose_name='执行动作'),
        ),
        migrations.AlterField(
            model_name='fieldlogicrule',
            name='action_value',
            field=models.JSONField(blank=True, null=True, verbose_name='动作值'),
        ),
        migrations.AlterField(
            model_name='fieldlogicrule',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logic_rules', to='conferenceApp.registrationform', verbose_name='所属表单'),
        ),
        migrations.AlterField(
            model_name='fieldlogicrule',
            name='operator',
            field=models.CharField(choices=[('equals', '等于'), ('not_equals', '不等于'), ('contains', '包含'), ('not_contains', '不包含'), ('greater_than', '大于'), ('less_than', '小于'), ('in', '在列表中'), ('not_in', '不在列表中'), ('starts_with', '以...开头'), ('ends_with', '以...结尾'), ('is_empty', '为空'), ('is_not_empty', '不为空'), ('between', '在...之间')], max_length=20, verbose_name='运算符'),
        ),
        migrations.AlterField(
            model_name='fieldlogicrule',
            name='value',
            field=models.JSONField(blank=True, null=True, verbose_name='比较值'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('description', models.TextField(blank=True, help_text='联系人的其他信息，如负责的具体事项等', verbose_name='描述')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='conferenceApp.conference')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人列表',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
