# Generated by Django 5.1 on 2024-11-30 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0002_alter_fieldlogicrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferenceApp.conference', verbose_name='会议'),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('confirmed', '已确认'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('checked_in', '已签到')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('conference', 'participant')},
        ),
    ]
