# Generated by Django 5.1 on 2024-12-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0002_add_formio_fields'),
        ('conferenceApp', '0004_conference_registration_form'),
    ]

    operations = [
    ]
