# Generated by Django 5.1 on 2024-12-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0005_merge_20241206_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationform',
            options={'verbose_name': '报名表单', 'verbose_name_plural': '报名表单'},
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='name',
            field=models.CharField(max_length=200, verbose_name='表单名称'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
