# Generated by Django 5.1 on 2024-12-08 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferenceApp', '0006_alter_registrationform_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference_notices',
            field=models.TextField(blank=True, help_text='包括行前准备、防疫要求等重要提示', null=True, verbose_name='会议注意事项'),
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_schedule',
            field=models.JSONField(blank=True, help_text='存储会议日程的详细安排', null=True, verbose_name='会议日程'),
        ),
        migrations.AddField(
            model_name='conference',
            name='dinner_seating_info',
            field=models.JSONField(blank=True, help_text='存储晚宴座位安排的JSON数据', null=True, verbose_name='晚宴座位信息'),
        ),
        migrations.AddField(
            model_name='conference',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='conference',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系电话'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问卷标题')),
                ('description', models.TextField(blank=True, verbose_name='问卷说明')),
                ('formio_schema', models.JSONField(verbose_name='Form.io Schema')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '问卷调查',
                'verbose_name_plural': '问卷调查',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceApp.conference', verbose_name='会议')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceApp.survey', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '问卷-会议关联',
                'verbose_name_plural': '问卷-会议关联',
                'unique_together': {('survey', 'conference')},
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='conferences',
            field=models.ManyToManyField(related_name='surveys', through='conferenceApp.SurveyConference', to='conferenceApp.conference', verbose_name='关联会议'),
        ),
        migrations.CreateModel(
            name='SurveyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='提醒名称')),
                ('description', models.TextField(blank=True, verbose_name='提醒描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('frequency', models.CharField(choices=[('once', '单次'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], max_length=20, verbose_name='提醒频率')),
                ('time', models.TimeField(verbose_name='提醒时间')),
                ('email_reminder', models.BooleanField(default=True, verbose_name='邮件提醒')),
                ('sms_reminder', models.BooleanField(default=False, verbose_name='短信提醒')),
                ('target_participants', models.CharField(choices=[('all', '所有参与者'), ('incomplete', '未完成者')], default='all', max_length=20, verbose_name='提醒对象')),
                ('email_subject_template', models.CharField(max_length=200, verbose_name='邮件主题模板')),
                ('email_body_template', models.TextField(verbose_name='邮件内容模板')),
                ('sms_template', models.CharField(max_length=500, verbose_name='短信内容模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='上次发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='conferenceApp.survey')),
            ],
            options={
                'verbose_name': '问卷提醒',
                'verbose_name_plural': '问卷提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('type', models.CharField(choices=[('email', '邮件'), ('sms', '短信')], max_length=10, verbose_name='提醒类型')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferenceApp.participant')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='conferenceApp.surveyreminder')),
            ],
            options={
                'verbose_name': '提醒日志',
                'verbose_name_plural': '提醒日志',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='模板标题')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('category', models.CharField(choices=[('satisfaction', '满意度调查'), ('feedback', '反馈收集'), ('registration', '报名登记'), ('evaluation', '会议评估'), ('other', '其他')], default='other', max_length=20, verbose_name='模板类别')),
                ('formio_schema', models.JSONField(verbose_name='Form.io Schema')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '问卷模板',
                'verbose_name_plural': '问卷模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(verbose_name='回答数据')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='conferenceApp.conference', verbose_name='关联会议')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='conferenceApp.survey', verbose_name='问卷')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='填写者')),
            ],
            options={
                'verbose_name': '问卷回答',
                'verbose_name_plural': '问卷回答',
                'ordering': ['-submitted_at'],
                'unique_together': {('survey', 'user', 'conference')},
            },
        ),
    ]
