# Generated by Django 5.1 on 2024-11-10 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gysdhChatApp', '0003_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publisher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='published_announcements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='can_private_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_publish_announcements',
            field=models.BooleanField(default=False),
        ),
    ]
