# Generated by Django 5.1 on 2024-11-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gysdhChatApp', '0004_announcement_publisher_user_can_private_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_event_staff',
            field=models.BooleanField(default=False),
        ),
    ]
