# Generated by Django 4.2.16 on 2024-11-18 06:21

from django.db import migrations


def copy_content_to_html_content(apps, schema_editor):
    Announcement = apps.get_model('gysdhChatApp', 'Announcement')
    for announcement in Announcement.objects.all():
        if not announcement.html_content and announcement.content:
            announcement.html_content = announcement.content
            announcement.save()

def reverse_copy_content(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("gysdhChatApp", "0018_announcement_html_content_alter_announcement_content"),
    ]

    operations = [
        migrations.RunPython(copy_content_to_html_content, reverse_copy_content),
    ]
