# Generated by Django 5.1.3 on 2024-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gysdhChatApp", "0020_systemsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="chat_area_title",
            field=models.CharField(
                default="会务沟通", max_length=100, verbose_name="聊天区域标题"
            ),
        ),
    ]
