# Generated by Django 5.1.3 on 2024-11-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gysdhChatApp", "0021_alter_systemsettings_chat_area_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="email_host",
            field=models.CharField(
                default="smtp.qq.com", max_length=100, verbose_name="邮件服务器"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_host_password",
            field=models.CharField(default="", max_length=100, verbose_name="授权码"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_host_user",
            field=models.EmailField(
                default="", max_length=255, verbose_name="邮箱账号"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_port",
            field=models.IntegerField(default=587, verbose_name="服务器端口"),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="email_use_tls",
            field=models.BooleanField(default=True, verbose_name="使用TLS"),
        ),
    ]
