# Generated by Django 5.1.3 on 2024-11-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gysdhChatApp", "0026_emailtemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="original_password",
        ),
        migrations.AddField(
            model_name="user",
            name="_encrypted_original_password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$original_pwd$trUOq96nUd4OiPZ9mMKcFYMhVuzL++kQ2QXbXHY4234=",
                max_length=128,
            ),
        ),
    ]
