# Generated by Django 5.1 on 2024-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gysdhChatApp', '0028_alter_user__encrypted_original_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_sticky', '-priority', '-timestamp'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='为空表示永不过期', null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_sticky',
            field=models.BooleanField(default=False, help_text='置顶的公告会始终显示在列表顶部', verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=1, verbose_name='优先级'),
        ),
    ]
